<?php

namespace AppBundle\Repository;

/**
 * SecurityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecurityRepository extends \Doctrine\ORM\EntityRepository
{
}
